image: Visual Studio 2017
configuration: Release

before_build:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%
    mkdir cmake_build
    cd cmake_build
    cmake --version

build_script: cmake c:\projects\q2vkpt

artifacts:
 - path: cmake_build\**\*.zip
