image: Visual Studio 2017
configuration: Release

install:
  ## Clone git submodules
   - git submodule update --init --recursive
  ## Prepare .sln with cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir cmake_build
  - cd cmake_build
  - cmake --version
  - cmake c:\projects\q2vkpt

build_script: msbuild "C:\projects\q2vkpt\cmake_build\quake2-pt.sln"

artifacts:
 - path: cmake_build\Release\**\*.*
